### ISSUE TITLE
Invalid ScalaCheck args: List(include, x)

### ISSUE THREAD

**Issue by zbeckman** [rickynils/scalacheck#193]
I just reported this over in the specs2 repo too (see https://github.com/etorreborre/specs2/issues/419) as I can't tell if this is a specs2-ScalaCheck integration issue, or just ScalaCheck.

Here's a recap:

Something broke within the past few days (or week) I believe. We have a stable project configuration. However, as of today when I tried to run a tagged test (I temporarily tag tests that I'm working on with an "x"), I get this:
```
[Glimpulse] $ ~testOnly utility.TestMail -- include x
[trace] Stack trace suppressed: run last test:testOnly for the full output.
[error] (test:testOnly) java.lang.Exception: Invalid ScalaCheck args: List(include, x)
[error] Total time: 0 s, completed Sep 28, 2015 5:31:57 PM
```
Nothing has changed in our build environment that I can think of. This is a practice I've used for literally years, and it's worked fine with specs2 and ScalaCheck.

Also, I'm not passing any test arguments (at all) in our build.sbt, as suggested in https://github.com/etorreborre/specs2/issues/414. Here's the build.sbt, just in case:

```
name := "Glimpulse"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.6"

resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/maven-releases/"

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

resolvers += Resolver.sonatypeRepo("releases")

resolvers += Resolver.sonatypeRepo("snapshots")

resolvers += "softprops-maven" at "http://dl.bintray.com/content/softprops/maven"

libraryDependencies ++= Seq(
	"com.zaxxer" % "HikariCP" % "2.3.8",
	"com.typesafe.slick" %% "slick" % "3.0.3",
	"com.typesafe.slick" %% "slick-extensions" % "3.0.0",
	"org.joda" % "joda-convert" % "1.7",
	"com.github.tototoshi" %% "slick-joda-mapper" % "2.0.0",
	"org.mindrot" % "jbcrypt" % "0.3m",
	"com.wix" %% "accord-core" % "0.4.2",
	"com.sksamuel.scrimage" %% "scrimage-core" % "2.0.2",
	"me.lessis" %% "courier" % "0.1.3",
	"com.google.code.findbugs" % "jsr305" % "2.0.3",
	"org.jvnet.mock-javamail" % "mock-javamail" % "1.9" % Test,
	"org.specs2" %% "specs2-scalacheck" % "3.6.4" % Test,
	specs2 % Test
)

// These options can be adjusted according to runtime (build) requirements. The most notable would be replacing
// the elide-below argument with an appropriate logging level. Use one of OFF (turn off output), MAXIMUM (which means
// elide, or truncate, the maximum amount of log output, so this is good for production because it will only log critical
// messages), WARNING (good for monitoring), INFO, and FINE (this latter will generate "fine grained" log output, in other
// words the maximum log output). You can also use MINIMUM to elide nothing (generate every possible log message).
//
// scalacOptions ++= Seq( "-deprecation", "-unchecked", "-language:postfixOps", "-Xelide-below", "OFF" ) // production mode!

scalacOptions ++= Seq("-feature", "-deprecation", "-unchecked", "-language:postfixOps", "-language:reflectiveCalls", "-language:implicitConversions", "-Xlint", "-Xelide-below", "MINIMUM" )

fork in run := true
```

**Comment by etorreborre** [comment]
I think you can work around this issue for now (until it is fixed in the next ScalaCheck version) by adding this to your sbt file:
```
testFrameworks := Seq(TestFrameworks.Specs2)
```

This will prevent arguments to be passed to the ScalaCheck runner.

**Comment by zbeckman** [comment]
Thanks @etorreborre that's fixed it for the time being. Is there another issue to watch or is this one staying open?

**Comment by etorreborre** [comment]
We should close this one and re-direct to https://github.com/rickynils/scalacheck/issues/173.

**Comment by rickynils** [comment]
@zbeckman What version are you using? The issue #173 should have been fixed in the 1.12.5 release.

**Comment by zbeckman** [comment]
Still seeing the problem with these dependencies (see the last two):
```
libraryDependencies ++= Seq(
	"com.zaxxer" % "HikariCP" % "2.3.8",
	"com.typesafe.slick" %% "slick" % "3.0.3",
	"com.typesafe.slick" %% "slick-extensions" % "3.0.0",
	"org.joda" % "joda-convert" % "1.7",
	"com.github.tototoshi" %% "slick-joda-mapper" % "2.0.0",
	"org.mindrot" % "jbcrypt" % "0.3m",
	"com.wix" %% "accord-core" % "0.4.2",
	"com.sksamuel.scrimage" %% "scrimage-core" % "2.0.2",
	"me.lessis" %% "courier" % "0.1.3",
	"com.google.code.findbugs" % "jsr305" % "2.0.3",
	"org.jvnet.mock-javamail" % "mock-javamail" % "1.9" % Test,
	"org.specs2" %% "specs2-scalacheck" % "3.6.4" % Test,
	specs2 % Test
)
```

**Comment by etorreborre** [comment]
That's because `specs2-scalacheck` depends on `scalacheck-1.12.4`. The next version will depend on `1.12.5`. So in the meantime you need to override the ScalaCheck dependency in your build. This should do:
```
libraryDependencies ++= Seq(
    "com.zaxxer" % "HikariCP" % "2.3.8",
    "com.typesafe.slick" %% "slick" % "3.0.3",
    "com.typesafe.slick" %% "slick-extensions" % "3.0.0",
    "org.joda" % "joda-convert" % "1.7",
    "com.github.tototoshi" %% "slick-joda-mapper" % "2.0.0",
    "org.mindrot" % "jbcrypt" % "0.3m",
    "com.wix" %% "accord-core" % "0.4.2",
    "com.sksamuel.scrimage" %% "scrimage-core" % "2.0.2",
    "me.lessis" %% "courier" % "0.1.3",
    "com.google.code.findbugs" % "jsr305" % "2.0.3",
    "org.jvnet.mock-javamail" % "mock-javamail" % "1.9" % Test,
    "org.scalacheck" %% "scalacheck" % "1.12.5" % Test,
    "org.specs2" %% "specs2-scalacheck" % "3.6.4" % Test,
    specs2 % Test
)
```
